import * as cdk from 'aws-cdk-lib';
import * as ec2  from 'aws-cdk-lib/aws-ec2';
import { Construct } from 'constructs';

export interface ComputeStackProps extends cdk.StackProps {
  bucketName:          string;
  instanceProfileName: string;
  ssmParameterPath:    string;
}

export class ComputeStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props: ComputeStackProps) {
    super(scope, id, props);

    // Ubuntu 22.04 LTS — latest AMI via AWS SSM (region-aware, no hardcoded ID)
    const amiId = ec2.MachineImage.fromSsmParameter(
      '/aws/service/canonical/ubuntu/server/22.04/stable/current/amd64/hvm/ebs-gp2/ami-id',
      { os: ec2.OperatingSystemType.LINUX },
    ).getImage(this).imageId;

    const userDataScript = `#!/bin/bash
set -euo pipefail
exec > >(tee /var/log/user-data.log | logger -t user-data) 2>&1

echo "==> Starting AILandings Demo bootstrap"

# ── System update & base packages ─────────────────────────────────────────────
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y software-properties-common curl unzip

# ── PHP 8.3 + Apache ──────────────────────────────────────────────────────────
add-apt-repository ppa:ondrej/php -y
apt-get update -y
apt-get install -y \\
  php8.3 php8.3-cli \\
  php8.3-mbstring php8.3-xml php8.3-zip \\
  php8.3-curl php8.3-bcmath \\
  php8.3-pdo php8.3-sqlite3 php8.3-mysql \\
  php8.3-gd php8.3-intl php8.3-tokenizer php8.3-fileinfo \\
  apache2 libapache2-mod-php8.3

# ── AWS CLI ───────────────────────────────────────────────────────────────────
curl -fsSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip
unzip -q /tmp/awscliv2.zip -d /tmp
/tmp/aws/install --update
rm -rf /tmp/aws /tmp/awscliv2.zip

# ── Resolve current region from IMDS ─────────────────────────────────────────
TOKEN=$(curl -sX PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 60")
REGION=$(curl -s -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/placement/region)
PUBLIC_IP=$(curl -s -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/public-ipv4 || echo "localhost")

# ── Read deployed version from SSM ────────────────────────────────────────────
VERSION=$(aws ssm get-parameter \\
  --name "${props.ssmParameterPath}" \\
  --region "$REGION" \\
  --query "Parameter.Value" \\
  --output text)

echo "==> Deploying version: $VERSION"

BUCKET="${props.bucketName}"
ARTIFACT_NAME="\${VERSION}.zip"
DEPLOY_DIR="/var/www/releases/$VERSION"
APP_LINK="/var/www/demo-app"

# ── Download & extract artifact ───────────────────────────────────────────────
mkdir -p "$DEPLOY_DIR"
aws s3 cp "s3://$BUCKET/demo-app/$ARTIFACT_NAME" "/tmp/$ARTIFACT_NAME" --region "$REGION"
unzip -q "/tmp/$ARTIFACT_NAME" -d "$DEPLOY_DIR"
rm -f "/tmp/$ARTIFACT_NAME"

# Symlink /var/www/demo-app → current release
ln -sfn "$DEPLOY_DIR" "$APP_LINK"

# ── Laravel production setup ──────────────────────────────────────────────────
cd "$APP_LINK"
# .env is shipped inside the artifact (key already generated by CI)
sed -i "s|APP_URL=.*|APP_URL=http://$PUBLIC_IP|" .env
sed -i "s|APP_ENV=.*|APP_ENV=debug|"         .env
sed -i "s|APP_DEBUG=.*|APP_DEBUG=false|"           .env
php artisan config:cache
php artisan route:cache
php artisan view:cache
php artisan storage:link --force || true
php artisan migrate --force

# ── Permissions ───────────────────────────────────────────────────────────────

chown -R www-data:www-data "$DEPLOY_DIR"

chmod -R 775 "$DEPLOY_DIR"

mkdir -p "$DEPLOY_DIR/storage"
mkdir -p "$DEPLOY_DIR/bootstrap/cache"

find "$DEPLOY_DIR/storage" -type d -exec chmod 775 {} \\;
find "$DEPLOY_DIR/bootstrap/cache" -type d -exec chmod 775 {} \\;

find "$DEPLOY_DIR/storage" -type f -exec chmod 664 {} \\;
find "$DEPLOY_DIR/bootstrap/cache" -type f -exec chmod 664 {} \\;

chmod g+s "$DEPLOY_DIR/storage"
chmod g+s "$DEPLOY_DIR/bootstrap/cache"

# ── Apache virtual host ───────────────────────────────────────────────────────
cat > /etc/apache2/sites-available/demo-app.conf <<'APACHEEOF'
<VirtualHost *:80>
    ServerAdmin webmaster@localhost
    DocumentRoot /var/www/demo-app/public

    <Directory /var/www/demo-app/public>
        AllowOverride All
        Require all granted
        Options -Indexes
    </Directory>

    ErrorLog  \${APACHE_LOG_DIR}/demo-app-error.log
    CustomLog \${APACHE_LOG_DIR}/demo-app-access.log combined
</VirtualHost>
APACHEEOF

a2ensite demo-app.conf
a2dissite 000-default.conf
a2enmod rewrite
systemctl enable apache2
systemctl restart apache2

echo "==> Bootstrap complete — version $VERSION is live"
`;

    const lt = new ec2.CfnLaunchTemplate(this, 'AILandingsDemoLaunchTemplate', {
      launchTemplateName: 'ailandings-demo-lt',
      launchTemplateData: {
        instanceType: 't3.micro',
        imageId:      amiId,
        iamInstanceProfile: { name: props.instanceProfileName },
        userData:     cdk.Fn.base64(userDataScript),
        monitoring:   { enabled: true },
        // IMDSv2 recommended; set httpTokens: 'required' for stricter security
        metadataOptions: {
          httpEndpoint: 'enabled',
          httpTokens:   'optional',
        },
      },
    });

    new cdk.CfnOutput(this, 'LaunchTemplateId',      { value: lt.ref });
    new cdk.CfnOutput(this, 'LaunchTemplateName',    { value: 'ailandings-demo-lt' });
  }
}
